#18 Поддержка функции ОбщегоНазначения.СкопироватьРекурсивно()
1C-Company/ssl-support pull request #33
Opened 2021-02-28 20:11 UTC by iArtemv

Для функции ОбщегоНазначения.СкопироватьРекурсивно() сделать возврат
входящего типа 1 параметра. Аналогично для
ОбщегоНазначенияКлиент.СкопироватьРекурсивно

2021-03-01 07:56 UTC, marmyshev requested changes
Еще нужно добавить инфу в README и документацию /docs - уже поставляется ввиде плагина

2021-03-01 09:15 UTC, artbear commented on tests/com.e1c.ssl.bsl.itests/src/com/e1c/ssl/bsl/itests/BslCommonFunctionsTest.java
> +        testingWorkspace.buildWorkspace();
Извините, что вмешиваюсь )

этот вызов testingWorkspace.buildWorkspace(); излишен, т.к. он уже вызывается в конце replaceFileContent

2021-03-01 09:33 UTC, artbear commented on tests/com.e1c.ssl.bsl.itests/src/com/e1c/ssl/bsl/itests/BslCommonFunctionsTest.java
> +        restoreState(oldFileContent, oldFile);
если тест упадет, то содержимое старого файла не восстановится (

2021-04-05 21:36 UTC, iArtemv commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionCopyRecursiveTypesComputer.java
> +        if (params.isEmpty() || params.size() > 2)
на текущий момент например в ERP второй параметр не используется, поэтому кажется пока не актуально. А мы можем простым способом вычислить значение второго параметра?

2021-04-07 13:21 UTC, marmyshev commented
@iArtemv  а доку по новой функции напишешь?

сейчас документация автоматом публикуется как эклип-сдокументация.

2021-04-07 14:41 UTC, iArtemv commented
Напишу, вчера не успел просто

2021-05-21 12:47 UTC, merged