#21 Поддержка функции ОбщегоНазанчения.ФиксированныеДанные()
1C-Company/ssl-support pull request #44
Opened 2021-05-10 12:49 UTC by iArtemv

В зависимости от типа входящих данных - возвращает такие же типы
"фиксированные"

2021-06-19 09:05 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionFixedDataTypesComputer.java
> +    private List<TypeItem> computeTypes(Invocation inv, Collection<Property> properties, TypeItem item)
`Invocation inv` - тут используется для контекста - предлагаю его сдлеать 3 параметром `EObject context`

2021-06-19 09:13 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionFixedDataTypesComputer.java
> +                type.getContextDef().getProperties().add(property);
@MaksimDzyuba можешь уточнить, здесь обязательно создавать новый инстанс DerivedProperty? разве нельзя (не лучше ли) переиспользовать существующий инстанс из другого типа как есть?

В данном случае - тут обычный тип (Структура, Массив, Соответствие) - заменяются на их "Фиксированный" аналог с сохранением исходных пользовательских свойств.

2021-06-19 09:18 UTC, marmyshev commented on tests/com.e1c.ssl.bsl.itests/workspace/CommonFunctions/src/CommonModules/СтроковыеФункцииКлиентСервер/Module.bsl
> +Функция ПодставитьПараметрыВСтроку(Знач ШаблонСтроки,
А точно нужно это тащить в тестову кофнигурацию? нам ведь не нужна рабочая БСП - в методах которые мы поддерживаем - вообще достаточно заглушки оставить на ненужные вызовы.

2021-06-19 09:20 UTC, marmyshev commented on tests/com.e1c.ssl.bsl.itests/workspace/CommonFunctions/src/Configuration/Configuration.mdo
> +  <commonModules>CommonModule.СтандартныеПодсистемыПовтИсп</commonModules>
Аналогичный вопрос - про то, что нужно ли тащить куски БСП если там нет или не будет в будущем функций API который будем поддерживать.

2021-06-21 08:49 UTC, MaksimDzyuba commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionFixedDataTypesComputer.java
> +                type.getContextDef().getProperties().add(property);
Можно и переиспользовать, но тогда надо в типе создавать специальный ContextDef, а именно ContextDefWithRefItem, у нас в коде есть места, как это делать

2021-06-22 16:30 UTC, marmyshev commented on tests/com.e1c.ssl.bsl.itests/resources/common-functions/common-module-fixed-data.bsl
> +&НаСервере
В общем модуле не должно быть директив

2021-06-22 22:59 UTC, MaksimDzyuba commented on tests/com.e1c.ssl.bsl.itests/resources/common-functions/common-module-fixed-data.bsl
> +&НаСервере
почему не должно, а если общий модуль и клиентский и серверный, да даже если он просто серверный, то задавать можно, правда смысла не имеет, или что ты имел ввиду, а то я увидел коммент и влез))

2021-06-23 05:28 UTC, iArtemv commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionFixedDataTypesComputer.java
> +                type.getContextDef().getProperties().add(property);
Внес изменения

2021-06-23 05:33 UTC, iArtemv commented on tests/com.e1c.ssl.bsl.itests/resources/common-functions/common-module-fixed-data.bsl
> +&НаСервере
ОК

2021-06-23 08:56 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionFixedDataTypesComputer.java
> +                type.getContextDef().getProperties().add(property);
Так исходный вопрос остался не решенным:
нужно ли здесь делать `DerivedProperty property = McoreFactory.eINSTANCE.createDerivedProperty();` то есть создавать копию объекта?

Можно ли переиспользовать инстанс DerivedProperty из исходного типа?

2021-06-23 09:05 UTC, marmyshev commented on tests/com.e1c.ssl.bsl.itests/resources/common-functions/common-module-fixed-array.bsl
> +    ФиксированныйМассив = ОбщегоНазначения.ФиксированныеДанные(Новый Массив);
А массив в параметрах ведь здесь не типизированный.

Сделай прям точный пример:

```bsl

Процедура Tест()

    Параметры = Новый Массив; // Массив из см. СложнаяСтруктура
    ФиксированныйМассив = ОбщегоНазначения.ФиксированныеДанные(Параметры);
    // Часть кода для документации
    Для каждого Элемент из ФиксированныйМассив Цикл
        Если Элемент.Ключ1 = 10 ИЛИ Элемент.Ключ2 = "Значение1" Тогда
             // Продолжаем...
        КонецЕсли
    КонецЦикла;

КонецПроцедуры

Функция СложнаяСтруктура()
    Возврат Новый Структура("Ключ1, Ключ2", 10, "Значение1";)
КонецФукцнии
```

2021-06-23 09:06 UTC, marmyshev commented on tests/com.e1c.ssl.bsl.itests/resources/common-functions/common-module-fixed-map.bsl
> +    ФиксированноеСоотвествие = ОбщегоНазначения.ФиксированныеДанные(Новый Соответствие);
Аналогично - параметр нетипизированный по типам ключа и значения соответствия.

2021-06-24 05:27 UTC, iArtemv commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionFixedDataTypesComputer.java
> +                type.getContextDef().getProperties().add(property);
Тоже поправил

2021-06-25 15:01 UTC, marmyshev requested changes

2021-06-25 17:30 UTC, marmyshev commented on CHANGELOG.md
> +* Поддержка функции ОбщегоНазанчения.ФиксированныеДанные()
перенести в 0.5

2021-06-28 05:10 UTC, iArtemv commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionFixedDataTypesComputer.java
> +                DerivedProperty property = (DerivedProperty)EcoreUtil2.cloneWithProxies(prop);
Использовать не копирую вероятно не получится из-за несовпадения свойств

2021-08-09 12:32 UTC, marmyshev requested changes
Вроде ничего больше такого не увидел.

2021-08-09 12:32 UTC, marmyshev commented on tests/com.e1c.ssl.bsl.itests/src/com/e1c/ssl/bsl/itests/BslCommonFunctionsTest.java
> +        assertEquals(IEObjectTypeNames.FIXED_ARRAY, McoreUtil.getTypeName(type));
Имя типа проверяется, но то, что тип имеет правильный тип элементов массива - тоже нужно проверять

2021-08-09 12:32 UTC, marmyshev commented on tests/com.e1c.ssl.bsl.itests/src/com/e1c/ssl/bsl/itests/BslCommonFunctionsTest.java
> +        assertEquals(IEObjectTypeNames.FIXED_MAP, McoreUtil.getTypeName(type));
Аналогично, нужно проверять еще что тип ключа и тип значения - те что ожидаются из входящих параметров.

2021-08-09 12:32 UTC, marmyshev commented on tests/com.e1c.ssl.bsl.itests/src/com/e1c/ssl/bsl/itests/BslCommonFunctionsTest.java
> +        expected.put("Ключ1", Lists.newArrayList("String")); //$NON-NLS-1$ //$NON-NLS-2$
тут лучше заменить на Map.of() и List.of() чтобы не использовать Гуаву лишний раз.

2021-08-09 12:32 UTC, marmyshev commented on tests/com.e1c.ssl.bsl.itests/resources/common-functions/common-module-fixed-array.bsl
> +    Возврат Новый Структура("Ключ1, Ключ2", 10, "Значение1");
Название процедуры не соответствует возвращаемому типу (массив) и возрвщаемое значение - структура  вместо массива.

2021-08-09 12:32 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionFixedDataTypesComputer.java
> +        List<TypeItem> collectionTypes = Lists.newArrayList();
Лучше заменить на new ArrayList<>(); избавиться от Гуавы

2021-08-09 12:32 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionFixedDataTypesComputer.java
> +            if (McoreUtil.getTypeName(type).equals(IEObjectTypeNames.STRUCTURE))
Тут и во всех сравнениях - нужно поменять местами объекты сравнения - результат функции и константу.

Константа никогда не будет null, а результат функции может вернуть null - поэтому - "золотое правило" при сравнении с константой - всегда идти от константы.

 `if (IEObjectTypeNames.STRUCTURE.equals(McoreUtil.getTypeName(type)))`

2021-08-10 17:30 UTC, merged