#52 ОбщегоНазначения.СкопироватьРекурсивно не учитывается второй параметр
1C-Company/ssl-support pull request #54
Opened 2021-07-18 15:11 UTC by popoffvg

#52 ОбщегоНазначения.СкопироватьРекурсивно не учитывается второй параметр

- Расширены тесты на вычисление типа возвращаемого значения функцией СкопироватьРекурсивно и выделены в отдельный класс
- Методы создания типа Соответствия, Структуры и Массива выделены в отдельный класс

Не учитывается случай преобразования Фиксированная коллекция -> обычная коллекция, если второй параметр = Ложь.

2021-07-20 13:25 UTC, marmyshev requested changes

2021-07-20 13:25 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/TypesComputerUtils.java
> +        ((TypeContainerRef)property.getTypeContainer()).getTypes().addAll(prop.getTypes());
Потенциальный  ClassCastExeption

2021-07-20 13:25 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/TypesComputerUtils.java
> +                DerivedProperty newProp = cloneProperty(prop);
Тут недавно обсуждали - можно ли не делать клонирование свойств каждый раз - а просто текущие переиспользовать нв новом типе. Надо бы ТУДУ добавить здесь - чтобы переделать по общему рефакторинг.

Но в данном случае - тут еще нужно правильно устанавливать setWritable() у свойства - если возвращается фиксированная структура - нужно удалять возможность записи. если была фиксированная а возвращается не фиксированная - **тогда** надо делать клонирование свойства и ставить возможность записи.

2021-07-20 13:25 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/TypesComputerUtils.java
> +        Pair<Collection<Property>, TypeItem> all = iterator.next();
Почему берется только первый тип? нужно обрабатывать все типы. Не забудь учесть - что когда переделаешь на входящий параметр вместо вычисления types - то либо передавать 1 тип входящий, либо тут корректно обрабатывать коллекции типов.

2021-07-20 13:25 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionCopyRecursiveTypesComputer.java
> +        switch (types.get(0).getName())
1. Нужно корректно обрабатывать все типы а не только первый.
2. Нельзя просто так взять имя типа - нужно использовать утилиту McoreUtil.getTypeName(type);

2021-07-20 13:25 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionCopyRecursiveTypesComputer.java
> +    protected IRuntimeVersionSupport versionSupport;
1. Так как это первый инжектинг здесь - предлагаю сразу переделать на инжектинг через конструктор - что более правильно
2. поле private final - если сабклассинг не планируется для этой функции.
3. Предлагаю тут сразу инжектить тот утильный класс TypesComputerUtils (который предлагаю переименовать более понятно) - в данном случае он ведь у тебя State-less поэтому получается вполне нормальный сервисный класс, который затем можно переиспользовать в других частях системы.

2021-07-20 13:25 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionCopyRecursiveTypesComputer.java
> +        if (returnFixCollection(params))
возможен дважды-вызов метода returnFixCollection - лучше выше результат присвоить переменной, т.к. второй вызов уже не вернет другое значение.

2021-07-20 13:25 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionCopyRecursiveTypesComputer.java
>          }
Уточни, если параметр 1 или если значение второго параметра "ложь" а входящий первый параметр - фиксированная структура - то что должно вернуться? (сейчас вернется as-is) Ведь с этого всё начиналось (бага), что нужно фиксированные данные "разфиксировать".

Неплохо бы на этот вариант так же тест добавить - вроде бы такой комбинации нет сейчас.

2021-07-20 16:25 UTC, popoffvg commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/TypesComputerUtils.java
> +        ((TypeContainerRef)property.getTypeContainer()).getTypes().addAll(prop.getTypes());
А в CommonFunctionValueTableRowToStructure#computeTypes так сделано, лучше там потом тоже поправить?

2021-07-20 19:31 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/TypesComputerUtils.java
> +        ((TypeContainerRef)property.getTypeContainer()).getTypes().addAll(prop.getTypes());
Мдя( недоаудировал там видимо.

2021-07-26 19:39 UTC, popoffvg commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionCopyRecursiveTypesComputer.java
> +        BooleanLiteral returnFixStructureParam = EcoreUtil2.getContainerOfType(expression, BooleanLiteral.class);
Трудозотраты по реализации немаленькие, а все равно останутся непокрытые случаи, когда параметр прилетает из функции.

То, что сделали у функции второй параметр - плохое решение. Лучше бы оставили без второго параметра и была комбинация СкопироватьРекурсивно + ФиксированныеДанные. 

Лучше оставить это ограничение =)

2021-07-26 20:17 UTC, popoffvg commented
@marmyshev исправил замечания. Глянь, пожалуйста.

2021-08-09 12:04 UTC, marmyshev requested changes
Кроме этих мелких замечаний  больше не нашел.

2021-08-09 12:04 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/TypesComputerHelper.java
> +        Type mapType = EcoreUtil2.cloneWithProxies((Type)EcoreUtil.resolve(type, context));
предлагаю заменить тип входящего параметра  `TypeItem type`  на `Type type` а в вызове безопасно проверять тип

2021-08-09 12:04 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/TypesComputerHelper.java
> +    protected List<TypeItem> createCustomMapType(List<TypeItem> keyTypes, List<TypeItem> valueTypes, Invocation context)
Invocation context - лучше заменить на EObject context

2021-08-09 12:08 UTC, marmyshev commented
Но еще посмотри, все ли комменты исправлены из предыдущего.

2021-08-11 19:14 UTC, marmyshev approved these changes

2021-08-11 20:01 UTC, merged