#1 Поддержка функции ОбщегоНазначения.ОписаниеСвойствОбъекта()
1C-Company/ssl-support pull request #7
Opened 2021-01-09 19:51 UTC by iArtemv

Для функции вычисляется список полей из параметров и возвращается
таблица с колонками из свойств объекта метаданных.

2021-01-11 10:14 UTC, marmyshev requested changes

2021-01-11 10:14 UTC, marmyshev commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionObjectPropertiesDetailsComputer.java
> +            (Type)ValueTableDynamicContextDefProvider.getColumnCollectionType(derivedType).allTypes().get(0);
метод `getColumnCollectionType()` может возвращать null, а далее небезопасное получение элемента и  небозопасный каст

2021-01-11 10:14 UTC, marmyshev commented on tests/com.e1c.ssl.bsl.itests/src/com/e1c/ssl/bsl/itests/BslCommonFunctionsTest.java
> +    public void testObjectPropertiesDetails() throws Exception
Посмотри паттерн наименования тестов `testFunction...` если тестируем функцию

2021-01-11 12:42 UTC, MaksimDzyuba commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionObjectPropertiesDetailsComputer.java
> +            part = part.trim();
Так может быть, что часть окажется пустой, поэтому стоит на это проверить. Если она пустая, то просто переходить к следующей

2021-01-11 12:42 UTC, MaksimDzyuba commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionObjectPropertiesDetailsComputer.java
> +    protected List<TypeItem> computeTypes(Invocation inv, String propetiesName, EList<Property> properties)
нет нужды использовать именно EList, если не планируется использовать методы именно этого интерфейса, достаточно List или Collection

2021-01-11 12:42 UTC, MaksimDzyuba commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionObjectPropertiesDetailsComputer.java
> +                    Property newProperty = EcoreUtil2.cloneWithProxies(property);
тут еще есть момент, что вот мы скопировали свойство, которое по сути могло бы быть DerivedProperty, у которого есть так называемый источник (см. метод getSource), сейчас источник не изменяется, верно ли это?

2021-01-11 12:42 UTC, MaksimDzyuba commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionObjectPropertiesDetailsComputer.java
> +                    Property newProperty = EcoreUtil2.cloneWithProxies(property);
тут еще может быть так, что у пришедшего свойства может тип лежать в TypeContainerDef, то есть по сути, таким подходом будет сделана еще одна копия ранее сконструированного типа. Может все же лучше честно написать код создания свойства, а не делать его копию

2021-01-11 17:38 UTC, marmyshev commented
нужно еще убрать "планируется" из доки https://github.com/1C-Company/ssl-support/blob/master/docs/README.md

2021-01-12 10:33 UTC, iArtemv commented on bundles/com.e1c.ssl.bsl/plugin.xml
> +            name="ObjectPropertiesDetails"
Меня в копию поставь:)

2021-01-12 18:56 UTC, iArtemv commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionObjectPropertiesDetailsComputer.java
> + */
@marmyshev по ссылке и в проекте по-разному стоит запятая
`* Copyright (C), 2021 1C-Soft LLC and others.`
`* Copyright (C) 2020, 1C-Soft LLC and others.`

2021-01-12 19:06 UTC, iArtemv commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionObjectPropertiesDetailsComputer.java
> +        String content = propetiesName.trim();
@marmyshev если метод сделать private, тогда наверное такой необходимости нет?

2021-01-12 20:55 UTC, iArtemv commented on bundles/com.e1c.ssl.bsl/src/com/e1c/ssl/bsl/CommonFunctionObjectPropertiesDetailsComputer.java
> + * Copyright (C) 2021, 1C
@marmyshev можешь пояснить?

2021-01-13 17:36 UTC, iArtemv commented on bundles/com.e1c.ssl.bsl/plugin.xml
> +            name="ObjectPropertiesDetails"
Посмотрел в их общем словаре, перевод совпадает

2021-02-19 14:29 UTC, marmyshev commented on CHANGELOG.md
> +* Поддержка функции ОбщегоНазначения.ОписаниеСвойствОбъекта()
Нужно перенести в версию 0.4

2021-02-19 14:30 UTC, marmyshev commented on tests/com.e1c.ssl.bsl.itests/src/com/e1c/ssl/bsl/itests/BslCommonFunctionsTest.java
> +        assertEquals("ValueTable", McoreUtil.getTypeName(type)); //$NON-NLS-1$
Можно бы использовать типы из констант IEObjectTypeNames (выше и ниже по коду)

2021-02-20 07:42 UTC, merged